name: Build and Deploy ASP.NET Core App

on:
  [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
  
    - name: Build Docker Image with Latest Tag
      run: | 
        docker build src/Deployment.Test.Backend/Api -t test-deployment:latest

    - name: Push Docker Images
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        docker push test-deployment:latest



