name: Build and Deploy ASP.NET Core App

on:
  [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Build Docker Image with Latest Tag
      run: | 
        docker build -f src/Deployment.Test.Backend/Api/Dockerfile -t test-deployment:latest src/Deployment.Test.Backend/Api

    - name: Push Docker Images
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        docker push test-deployment:latest